import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/layout'
import { createClient } from 'contentful'
import { Inter } from 'next/font/google'
import Hero from './components/Hero'
import Startpage from './components/Startpage'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(){

  const client = createClient({
    space: "9dfuiiplny0l",
    accessToken: "kpEeblBQnevucoN7lG8BHqgQb-8XHcHYp-FV5tF4B5g",
  })

  const response = await client.getEntries({ content_type: 'products'})
  const response2 = await client.getEntries({ content_type: 'startpage'})

  return {
    props: {
      products: response.items,
      startpage: response2.items
    }
  }
}

export default function Home({products, startpage}) {

  // console.log(products)
  // console.log(startpage)
  return (

    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero startpage={startpage}/>
        <Startpage startpage={startpage} products={products}/>
      </Layout>
    </>
  )
}
